COMMANDS_CLOSE_WINDOW = "7"
COMMANDS_TAB_WINDOW = "8"
COMMANDS_ENTER = "9"
COMMANDS_SCROLL_VERTICAL_DOWN = "10"
COMMANDS_SCROLL_VERTICAL_UP = "11"
COMMANDS_ESC = "12"
COMMANDS_MOUSE_LEFT_CLICK = "13"
COMMANDS_MOUSE_RIGHT_CLICK = "14"
COMMANDS_MOUSE_LEFT_LONG_CLICK = "15"


